### ISSUE TITLE
Rename *Decorator classes.

### ISSUE THREAD

**Issue by dmfs** [dmfs/http-client-essentials-suite#22]
No class should be named like `*Decorator`. In particular we should rename the classes in `decoration` (not sure if there are more of that kind).
For decorators we should stick to our decorator naming scheme. If that doesn't work the name should end like the interface that's implemented.
 For `RequestHeaderDecorator` we could pick something like `HeaderDecorated` or `CustomHeaderRequest`. Other ideas?

**Comment by lemonboston** [comment]
I agree and I like `HeaderDecorated`.
Only those 3 classes have "Decorator" in their names in this project, so they would be renamed as following then:

`RequestEntityDecorator` -> `EntityDecorated`
`RequestHeaderDecorator` -> `HeaderDecorated`
`RequestResponseDecorator` -> `ResponseDecorated`

Ok?

**Comment by dmfs** [comment]
Looks good. Merged it.
